### ISSUE TITLE
[BUG] ProductTest 동작하지 않는 현상

### ISSUE THREAD

**Issue by f-lab-lion** [f-lab-edu/buy-by-team#72]
## Describe the bug
Product test코드에서 이미 없어진 `serialNum`를 사용하기때문에 오류발생

127번줄에서 오류발생 -> 

https://github.com/f-lab-edu/buy-by-team/blob/897bd886b95bdf1c0c32a0c9ea55b3b02b669008/src/test/java/com/flab/bbt/product/service/ProductServiceTest.java#L124-L132

---
https://github.com/f-lab-edu/buy-by-team/blob/6b7fdf6bdf9cefb5e0899285121d9c101d437e6b/src/main/java/com/flab/bbt/product/domain/Product.java#L13-L22

**Comment by hoonpark7442** [comment]
#57 풀리퀘스트에서 이 부분 수정이 들어가 있습니다. 머지되면 해당 이슈도 닫도록 하겠습니다.
