### ISSUE TITLE
[BUG] 코드 안정화

### ISSUE THREAD

**Issue by hoonpark7442** [f-lab-edu/buy-by-team#94]
## Describe the bug
현재 작동안하는 코드들 수정 및 테스트 코드 작성

**Comment by f-lab-lion** [comment]
`To Reproduce` 이하의 항목은 사용하지 않으면 제거해주세요~
템플릿 항목이지만, 실제 이슈와 일치하지 않는 항목이라면 제거하는것이 보기에 편합니다.
